/*
 * This source file was generated by the Gradle 'init' task
 */
package javaex;

class AppTest {
    // No test available: App class no longer has getGreeting().
    // Add new tests for menu or utility functions if needed.
}
